# site settings

title: Welcome to manu
description: Todavia no defini el uso directo de esta web pero mira el pinguinito que facherito que esta.
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://frosimanuel.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/frosimanuel/frosimanuel.github.io

# author settings

author:
  name: Manuel Frosi
  email: username@whocares.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: username
  github: frosimanuel
  instagram: username
  linkedin: manuel-frosi
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
